/**
 * Autogenerated by Thrift Compiler (0.9.1)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package com.sidney.dbsyncserver.tserializ.admanager;

import org.apache.thrift.scheme.IScheme;
import org.apache.thrift.scheme.SchemeFactory;
import org.apache.thrift.scheme.StandardScheme;

import org.apache.thrift.scheme.TupleScheme;
import org.apache.thrift.protocol.TTupleProtocol;
import org.apache.thrift.protocol.TProtocolException;
import org.apache.thrift.EncodingUtils;
import org.apache.thrift.TException;
import org.apache.thrift.async.AsyncMethodCallback;
import org.apache.thrift.server.AbstractNonblockingServer.*;
import java.util.List;
import java.util.ArrayList;
import java.util.Map;
import java.util.HashMap;
import java.util.EnumMap;
import java.util.Set;
import java.util.HashSet;
import java.util.EnumSet;
import java.util.Collections;
import java.util.BitSet;
import java.nio.ByteBuffer;
import java.util.Arrays;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

public class TDbSync_AdManager_Config implements org.apache.thrift.TBase<TDbSync_AdManager_Config, TDbSync_AdManager_Config._Fields>, java.io.Serializable, Cloneable, Comparable<TDbSync_AdManager_Config> {
  private static final org.apache.thrift.protocol.TStruct STRUCT_DESC = new org.apache.thrift.protocol.TStruct("TDbSync_AdManager_Config");

  private static final org.apache.thrift.protocol.TField KEY_FIELD_DESC = new org.apache.thrift.protocol.TField("key", org.apache.thrift.protocol.TType.STRING, (short)1);
  private static final org.apache.thrift.protocol.TField STATUS_FIELD_DESC = new org.apache.thrift.protocol.TField("status", org.apache.thrift.protocol.TType.I32, (short)2);
  private static final org.apache.thrift.protocol.TField LAST_CHANGED_FIELD_DESC = new org.apache.thrift.protocol.TField("lastChanged", org.apache.thrift.protocol.TType.STRING, (short)3);
  private static final org.apache.thrift.protocol.TField VALUE1_FIELD_DESC = new org.apache.thrift.protocol.TField("value1", org.apache.thrift.protocol.TType.STRING, (short)4);
  private static final org.apache.thrift.protocol.TField VALUE2_FIELD_DESC = new org.apache.thrift.protocol.TField("value2", org.apache.thrift.protocol.TType.STRING, (short)5);
  private static final org.apache.thrift.protocol.TField VALUE3_FIELD_DESC = new org.apache.thrift.protocol.TField("value3", org.apache.thrift.protocol.TType.STRING, (short)6);

  private static final Map<Class<? extends IScheme>, SchemeFactory> schemes = new HashMap<Class<? extends IScheme>, SchemeFactory>();
  static {
    schemes.put(StandardScheme.class, new TDbSync_AdManager_ConfigStandardSchemeFactory());
    schemes.put(TupleScheme.class, new TDbSync_AdManager_ConfigTupleSchemeFactory());
  }

  public String key; // required
  public int status; // required
  public String lastChanged; // required
  public String value1; // required
  public String value2; // required
  public String value3; // required

  /** The set of fields this struct contains, along with convenience methods for finding and manipulating them. */
  public enum _Fields implements org.apache.thrift.TFieldIdEnum {
    KEY((short)1, "key"),
    STATUS((short)2, "status"),
    LAST_CHANGED((short)3, "lastChanged"),
    VALUE1((short)4, "value1"),
    VALUE2((short)5, "value2"),
    VALUE3((short)6, "value3");

    private static final Map<String, _Fields> byName = new HashMap<String, _Fields>();

    static {
      for (_Fields field : EnumSet.allOf(_Fields.class)) {
        byName.put(field.getFieldName(), field);
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, or null if its not found.
     */
    public static _Fields findByThriftId(int fieldId) {
      switch(fieldId) {
        case 1: // KEY
          return KEY;
        case 2: // STATUS
          return STATUS;
        case 3: // LAST_CHANGED
          return LAST_CHANGED;
        case 4: // VALUE1
          return VALUE1;
        case 5: // VALUE2
          return VALUE2;
        case 6: // VALUE3
          return VALUE3;
        default:
          return null;
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, throwing an exception
     * if it is not found.
     */
    public static _Fields findByThriftIdOrThrow(int fieldId) {
      _Fields fields = findByThriftId(fieldId);
      if (fields == null) throw new IllegalArgumentException("Field " + fieldId + " doesn't exist!");
      return fields;
    }

    /**
     * Find the _Fields constant that matches name, or null if its not found.
     */
    public static _Fields findByName(String name) {
      return byName.get(name);
    }

    private final short _thriftId;
    private final String _fieldName;

    _Fields(short thriftId, String fieldName) {
      _thriftId = thriftId;
      _fieldName = fieldName;
    }

    public short getThriftFieldId() {
      return _thriftId;
    }

    public String getFieldName() {
      return _fieldName;
    }
  }

  // isset id assignments
  private static final int __STATUS_ISSET_ID = 0;
  private byte __isset_bitfield = 0;
  public static final Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> metaDataMap;
  static {
    Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> tmpMap = new EnumMap<_Fields, org.apache.thrift.meta_data.FieldMetaData>(_Fields.class);
    tmpMap.put(_Fields.KEY, new org.apache.thrift.meta_data.FieldMetaData("key", org.apache.thrift.TFieldRequirementType.REQUIRED, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.STRING)));
    tmpMap.put(_Fields.STATUS, new org.apache.thrift.meta_data.FieldMetaData("status", org.apache.thrift.TFieldRequirementType.REQUIRED, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.I32)));
    tmpMap.put(_Fields.LAST_CHANGED, new org.apache.thrift.meta_data.FieldMetaData("lastChanged", org.apache.thrift.TFieldRequirementType.REQUIRED, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.STRING)));
    tmpMap.put(_Fields.VALUE1, new org.apache.thrift.meta_data.FieldMetaData("value1", org.apache.thrift.TFieldRequirementType.REQUIRED, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.STRING)));
    tmpMap.put(_Fields.VALUE2, new org.apache.thrift.meta_data.FieldMetaData("value2", org.apache.thrift.TFieldRequirementType.REQUIRED, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.STRING)));
    tmpMap.put(_Fields.VALUE3, new org.apache.thrift.meta_data.FieldMetaData("value3", org.apache.thrift.TFieldRequirementType.REQUIRED, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.STRING)));
    metaDataMap = Collections.unmodifiableMap(tmpMap);
    org.apache.thrift.meta_data.FieldMetaData.addStructMetaDataMap(TDbSync_AdManager_Config.class, metaDataMap);
  }

  public TDbSync_AdManager_Config() {
  }

  public TDbSync_AdManager_Config(
    String key,
    int status,
    String lastChanged,
    String value1,
    String value2,
    String value3)
  {
    this();
    this.key = key;
    this.status = status;
    setStatusIsSet(true);
    this.lastChanged = lastChanged;
    this.value1 = value1;
    this.value2 = value2;
    this.value3 = value3;
  }

  /**
   * Performs a deep copy on <i>other</i>.
   */
  public TDbSync_AdManager_Config(TDbSync_AdManager_Config other) {
    __isset_bitfield = other.__isset_bitfield;
    if (other.isSetKey()) {
      this.key = other.key;
    }
    this.status = other.status;
    if (other.isSetLastChanged()) {
      this.lastChanged = other.lastChanged;
    }
    if (other.isSetValue1()) {
      this.value1 = other.value1;
    }
    if (other.isSetValue2()) {
      this.value2 = other.value2;
    }
    if (other.isSetValue3()) {
      this.value3 = other.value3;
    }
  }

  public TDbSync_AdManager_Config deepCopy() {
    return new TDbSync_AdManager_Config(this);
  }

  @Override
  public void clear() {
    this.key = null;
    setStatusIsSet(false);
    this.status = 0;
    this.lastChanged = null;
    this.value1 = null;
    this.value2 = null;
    this.value3 = null;
  }

  public String getKey() {
    return this.key;
  }

  public TDbSync_AdManager_Config setKey(String key) {
    this.key = key;
    return this;
  }

  public void unsetKey() {
    this.key = null;
  }

  /** Returns true if field key is set (has been assigned a value) and false otherwise */
  public boolean isSetKey() {
    return this.key != null;
  }

  public void setKeyIsSet(boolean value) {
    if (!value) {
      this.key = null;
    }
  }

  public int getStatus() {
    return this.status;
  }

  public TDbSync_AdManager_Config setStatus(int status) {
    this.status = status;
    setStatusIsSet(true);
    return this;
  }

  public void unsetStatus() {
    __isset_bitfield = EncodingUtils.clearBit(__isset_bitfield, __STATUS_ISSET_ID);
  }

  /** Returns true if field status is set (has been assigned a value) and false otherwise */
  public boolean isSetStatus() {
    return EncodingUtils.testBit(__isset_bitfield, __STATUS_ISSET_ID);
  }

  public void setStatusIsSet(boolean value) {
    __isset_bitfield = EncodingUtils.setBit(__isset_bitfield, __STATUS_ISSET_ID, value);
  }

  public String getLastChanged() {
    return this.lastChanged;
  }

  public TDbSync_AdManager_Config setLastChanged(String lastChanged) {
    this.lastChanged = lastChanged;
    return this;
  }

  public void unsetLastChanged() {
    this.lastChanged = null;
  }

  /** Returns true if field lastChanged is set (has been assigned a value) and false otherwise */
  public boolean isSetLastChanged() {
    return this.lastChanged != null;
  }

  public void setLastChangedIsSet(boolean value) {
    if (!value) {
      this.lastChanged = null;
    }
  }

  public String getValue1() {
    return this.value1;
  }

  public TDbSync_AdManager_Config setValue1(String value1) {
    this.value1 = value1;
    return this;
  }

  public void unsetValue1() {
    this.value1 = null;
  }

  /** Returns true if field value1 is set (has been assigned a value) and false otherwise */
  public boolean isSetValue1() {
    return this.value1 != null;
  }

  public void setValue1IsSet(boolean value) {
    if (!value) {
      this.value1 = null;
    }
  }

  public String getValue2() {
    return this.value2;
  }

  public TDbSync_AdManager_Config setValue2(String value2) {
    this.value2 = value2;
    return this;
  }

  public void unsetValue2() {
    this.value2 = null;
  }

  /** Returns true if field value2 is set (has been assigned a value) and false otherwise */
  public boolean isSetValue2() {
    return this.value2 != null;
  }

  public void setValue2IsSet(boolean value) {
    if (!value) {
      this.value2 = null;
    }
  }

  public String getValue3() {
    return this.value3;
  }

  public TDbSync_AdManager_Config setValue3(String value3) {
    this.value3 = value3;
    return this;
  }

  public void unsetValue3() {
    this.value3 = null;
  }

  /** Returns true if field value3 is set (has been assigned a value) and false otherwise */
  public boolean isSetValue3() {
    return this.value3 != null;
  }

  public void setValue3IsSet(boolean value) {
    if (!value) {
      this.value3 = null;
    }
  }

  public void setFieldValue(_Fields field, Object value) {
    switch (field) {
    case KEY:
      if (value == null) {
        unsetKey();
      } else {
        setKey((String)value);
      }
      break;

    case STATUS:
      if (value == null) {
        unsetStatus();
      } else {
        setStatus((Integer)value);
      }
      break;

    case LAST_CHANGED:
      if (value == null) {
        unsetLastChanged();
      } else {
        setLastChanged((String)value);
      }
      break;

    case VALUE1:
      if (value == null) {
        unsetValue1();
      } else {
        setValue1((String)value);
      }
      break;

    case VALUE2:
      if (value == null) {
        unsetValue2();
      } else {
        setValue2((String)value);
      }
      break;

    case VALUE3:
      if (value == null) {
        unsetValue3();
      } else {
        setValue3((String)value);
      }
      break;

    }
  }

  public Object getFieldValue(_Fields field) {
    switch (field) {
    case KEY:
      return getKey();

    case STATUS:
      return Integer.valueOf(getStatus());

    case LAST_CHANGED:
      return getLastChanged();

    case VALUE1:
      return getValue1();

    case VALUE2:
      return getValue2();

    case VALUE3:
      return getValue3();

    }
    throw new IllegalStateException();
  }

  /** Returns true if field corresponding to fieldID is set (has been assigned a value) and false otherwise */
  public boolean isSet(_Fields field) {
    if (field == null) {
      throw new IllegalArgumentException();
    }

    switch (field) {
    case KEY:
      return isSetKey();
    case STATUS:
      return isSetStatus();
    case LAST_CHANGED:
      return isSetLastChanged();
    case VALUE1:
      return isSetValue1();
    case VALUE2:
      return isSetValue2();
    case VALUE3:
      return isSetValue3();
    }
    throw new IllegalStateException();
  }

  @Override
  public boolean equals(Object that) {
    if (that == null)
      return false;
    if (that instanceof TDbSync_AdManager_Config)
      return this.equals((TDbSync_AdManager_Config)that);
    return false;
  }

  public boolean equals(TDbSync_AdManager_Config that) {
    if (that == null)
      return false;

    boolean this_present_key = true && this.isSetKey();
    boolean that_present_key = true && that.isSetKey();
    if (this_present_key || that_present_key) {
      if (!(this_present_key && that_present_key))
        return false;
      if (!this.key.equals(that.key))
        return false;
    }

    boolean this_present_status = true;
    boolean that_present_status = true;
    if (this_present_status || that_present_status) {
      if (!(this_present_status && that_present_status))
        return false;
      if (this.status != that.status)
        return false;
    }

    boolean this_present_lastChanged = true && this.isSetLastChanged();
    boolean that_present_lastChanged = true && that.isSetLastChanged();
    if (this_present_lastChanged || that_present_lastChanged) {
      if (!(this_present_lastChanged && that_present_lastChanged))
        return false;
      if (!this.lastChanged.equals(that.lastChanged))
        return false;
    }

    boolean this_present_value1 = true && this.isSetValue1();
    boolean that_present_value1 = true && that.isSetValue1();
    if (this_present_value1 || that_present_value1) {
      if (!(this_present_value1 && that_present_value1))
        return false;
      if (!this.value1.equals(that.value1))
        return false;
    }

    boolean this_present_value2 = true && this.isSetValue2();
    boolean that_present_value2 = true && that.isSetValue2();
    if (this_present_value2 || that_present_value2) {
      if (!(this_present_value2 && that_present_value2))
        return false;
      if (!this.value2.equals(that.value2))
        return false;
    }

    boolean this_present_value3 = true && this.isSetValue3();
    boolean that_present_value3 = true && that.isSetValue3();
    if (this_present_value3 || that_present_value3) {
      if (!(this_present_value3 && that_present_value3))
        return false;
      if (!this.value3.equals(that.value3))
        return false;
    }

    return true;
  }

  @Override
  public int hashCode() {
    return 0;
  }

  @Override
  public int compareTo(TDbSync_AdManager_Config other) {
    if (!getClass().equals(other.getClass())) {
      return getClass().getName().compareTo(other.getClass().getName());
    }

    int lastComparison = 0;

    lastComparison = Boolean.valueOf(isSetKey()).compareTo(other.isSetKey());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetKey()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.key, other.key);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = Boolean.valueOf(isSetStatus()).compareTo(other.isSetStatus());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetStatus()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.status, other.status);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = Boolean.valueOf(isSetLastChanged()).compareTo(other.isSetLastChanged());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetLastChanged()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.lastChanged, other.lastChanged);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = Boolean.valueOf(isSetValue1()).compareTo(other.isSetValue1());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetValue1()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.value1, other.value1);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = Boolean.valueOf(isSetValue2()).compareTo(other.isSetValue2());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetValue2()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.value2, other.value2);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = Boolean.valueOf(isSetValue3()).compareTo(other.isSetValue3());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetValue3()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.value3, other.value3);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    return 0;
  }

  public _Fields fieldForId(int fieldId) {
    return _Fields.findByThriftId(fieldId);
  }

  public void read(org.apache.thrift.protocol.TProtocol iprot) throws org.apache.thrift.TException {
    schemes.get(iprot.getScheme()).getScheme().read(iprot, this);
  }

  public void write(org.apache.thrift.protocol.TProtocol oprot) throws org.apache.thrift.TException {
    schemes.get(oprot.getScheme()).getScheme().write(oprot, this);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder("TDbSync_AdManager_Config(");
    boolean first = true;

    sb.append("key:");
    if (this.key == null) {
      sb.append("null");
    } else {
      sb.append(this.key);
    }
    first = false;
    if (!first) sb.append(", ");
    sb.append("status:");
    sb.append(this.status);
    first = false;
    if (!first) sb.append(", ");
    sb.append("lastChanged:");
    if (this.lastChanged == null) {
      sb.append("null");
    } else {
      sb.append(this.lastChanged);
    }
    first = false;
    if (!first) sb.append(", ");
    sb.append("value1:");
    if (this.value1 == null) {
      sb.append("null");
    } else {
      sb.append(this.value1);
    }
    first = false;
    if (!first) sb.append(", ");
    sb.append("value2:");
    if (this.value2 == null) {
      sb.append("null");
    } else {
      sb.append(this.value2);
    }
    first = false;
    if (!first) sb.append(", ");
    sb.append("value3:");
    if (this.value3 == null) {
      sb.append("null");
    } else {
      sb.append(this.value3);
    }
    first = false;
    sb.append(")");
    return sb.toString();
  }

  public void validate() throws org.apache.thrift.TException {
    // check for required fields
    if (key == null) {
      throw new org.apache.thrift.protocol.TProtocolException("Required field 'key' was not present! Struct: " + toString());
    }
    // alas, we cannot check 'status' because it's a primitive and you chose the non-beans generator.
    if (lastChanged == null) {
      throw new org.apache.thrift.protocol.TProtocolException("Required field 'lastChanged' was not present! Struct: " + toString());
    }
    if (value1 == null) {
      throw new org.apache.thrift.protocol.TProtocolException("Required field 'value1' was not present! Struct: " + toString());
    }
    if (value2 == null) {
      throw new org.apache.thrift.protocol.TProtocolException("Required field 'value2' was not present! Struct: " + toString());
    }
    if (value3 == null) {
      throw new org.apache.thrift.protocol.TProtocolException("Required field 'value3' was not present! Struct: " + toString());
    }
    // check for sub-struct validity
  }

  private void writeObject(java.io.ObjectOutputStream out) throws java.io.IOException {
    try {
      write(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(out)));
    } catch (org.apache.thrift.TException te) {
      throw new java.io.IOException(te);
    }
  }

  private void readObject(java.io.ObjectInputStream in) throws java.io.IOException, ClassNotFoundException {
    try {
      // it doesn't seem like you should have to do this, but java serialization is wacky, and doesn't call the default constructor.
      __isset_bitfield = 0;
      read(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(in)));
    } catch (org.apache.thrift.TException te) {
      throw new java.io.IOException(te);
    }
  }

  private static class TDbSync_AdManager_ConfigStandardSchemeFactory implements SchemeFactory {
    public TDbSync_AdManager_ConfigStandardScheme getScheme() {
      return new TDbSync_AdManager_ConfigStandardScheme();
    }
  }

  private static class TDbSync_AdManager_ConfigStandardScheme extends StandardScheme<TDbSync_AdManager_Config> {

    public void read(org.apache.thrift.protocol.TProtocol iprot, TDbSync_AdManager_Config struct) throws org.apache.thrift.TException {
      org.apache.thrift.protocol.TField schemeField;
      iprot.readStructBegin();
      while (true)
      {
        schemeField = iprot.readFieldBegin();
        if (schemeField.type == org.apache.thrift.protocol.TType.STOP) { 
          break;
        }
        switch (schemeField.id) {
          case 1: // KEY
            if (schemeField.type == org.apache.thrift.protocol.TType.STRING) {
              struct.key = iprot.readString();
              struct.setKeyIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 2: // STATUS
            if (schemeField.type == org.apache.thrift.protocol.TType.I32) {
              struct.status = iprot.readI32();
              struct.setStatusIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 3: // LAST_CHANGED
            if (schemeField.type == org.apache.thrift.protocol.TType.STRING) {
              struct.lastChanged = iprot.readString();
              struct.setLastChangedIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 4: // VALUE1
            if (schemeField.type == org.apache.thrift.protocol.TType.STRING) {
              struct.value1 = iprot.readString();
              struct.setValue1IsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 5: // VALUE2
            if (schemeField.type == org.apache.thrift.protocol.TType.STRING) {
              struct.value2 = iprot.readString();
              struct.setValue2IsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 6: // VALUE3
            if (schemeField.type == org.apache.thrift.protocol.TType.STRING) {
              struct.value3 = iprot.readString();
              struct.setValue3IsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          default:
            org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
        }
        iprot.readFieldEnd();
      }
      iprot.readStructEnd();

      // check for required fields of primitive type, which can't be checked in the validate method
      if (!struct.isSetStatus()) {
        throw new org.apache.thrift.protocol.TProtocolException("Required field 'status' was not found in serialized data! Struct: " + toString());
      }
      struct.validate();
    }

    public void write(org.apache.thrift.protocol.TProtocol oprot, TDbSync_AdManager_Config struct) throws org.apache.thrift.TException {
      struct.validate();

      oprot.writeStructBegin(STRUCT_DESC);
      if (struct.key != null) {
        oprot.writeFieldBegin(KEY_FIELD_DESC);
        oprot.writeString(struct.key);
        oprot.writeFieldEnd();
      }
      oprot.writeFieldBegin(STATUS_FIELD_DESC);
      oprot.writeI32(struct.status);
      oprot.writeFieldEnd();
      if (struct.lastChanged != null) {
        oprot.writeFieldBegin(LAST_CHANGED_FIELD_DESC);
        oprot.writeString(struct.lastChanged);
        oprot.writeFieldEnd();
      }
      if (struct.value1 != null) {
        oprot.writeFieldBegin(VALUE1_FIELD_DESC);
        oprot.writeString(struct.value1);
        oprot.writeFieldEnd();
      }
      if (struct.value2 != null) {
        oprot.writeFieldBegin(VALUE2_FIELD_DESC);
        oprot.writeString(struct.value2);
        oprot.writeFieldEnd();
      }
      if (struct.value3 != null) {
        oprot.writeFieldBegin(VALUE3_FIELD_DESC);
        oprot.writeString(struct.value3);
        oprot.writeFieldEnd();
      }
      oprot.writeFieldStop();
      oprot.writeStructEnd();
    }

  }

  private static class TDbSync_AdManager_ConfigTupleSchemeFactory implements SchemeFactory {
    public TDbSync_AdManager_ConfigTupleScheme getScheme() {
      return new TDbSync_AdManager_ConfigTupleScheme();
    }
  }

  private static class TDbSync_AdManager_ConfigTupleScheme extends TupleScheme<TDbSync_AdManager_Config> {

    @Override
    public void write(org.apache.thrift.protocol.TProtocol prot, TDbSync_AdManager_Config struct) throws org.apache.thrift.TException {
      TTupleProtocol oprot = (TTupleProtocol) prot;
      oprot.writeString(struct.key);
      oprot.writeI32(struct.status);
      oprot.writeString(struct.lastChanged);
      oprot.writeString(struct.value1);
      oprot.writeString(struct.value2);
      oprot.writeString(struct.value3);
    }

    @Override
    public void read(org.apache.thrift.protocol.TProtocol prot, TDbSync_AdManager_Config struct) throws org.apache.thrift.TException {
      TTupleProtocol iprot = (TTupleProtocol) prot;
      struct.key = iprot.readString();
      struct.setKeyIsSet(true);
      struct.status = iprot.readI32();
      struct.setStatusIsSet(true);
      struct.lastChanged = iprot.readString();
      struct.setLastChangedIsSet(true);
      struct.value1 = iprot.readString();
      struct.setValue1IsSet(true);
      struct.value2 = iprot.readString();
      struct.setValue2IsSet(true);
      struct.value3 = iprot.readString();
      struct.setValue3IsSet(true);
    }
  }

}

