/**
 * Autogenerated by Thrift Compiler (0.9.1)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package com.sidney.dbsyncserver.tserializ.dsp;

import org.apache.thrift.scheme.IScheme;
import org.apache.thrift.scheme.SchemeFactory;
import org.apache.thrift.scheme.StandardScheme;

import org.apache.thrift.scheme.TupleScheme;
import org.apache.thrift.protocol.TTupleProtocol;
import org.apache.thrift.protocol.TProtocolException;
import org.apache.thrift.EncodingUtils;
import org.apache.thrift.TException;
import org.apache.thrift.async.AsyncMethodCallback;
import org.apache.thrift.server.AbstractNonblockingServer.*;
import java.util.List;
import java.util.ArrayList;
import java.util.Map;
import java.util.HashMap;
import java.util.EnumMap;
import java.util.Set;
import java.util.HashSet;
import java.util.EnumSet;
import java.util.Collections;
import java.util.BitSet;
import java.nio.ByteBuffer;
import java.util.Arrays;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

public class TDbSync_Dsp_Media_Buy_Target_Audience implements org.apache.thrift.TBase<TDbSync_Dsp_Media_Buy_Target_Audience, TDbSync_Dsp_Media_Buy_Target_Audience._Fields>, java.io.Serializable, Cloneable, Comparable<TDbSync_Dsp_Media_Buy_Target_Audience> {
  private static final org.apache.thrift.protocol.TStruct STRUCT_DESC = new org.apache.thrift.protocol.TStruct("TDbSync_Dsp_Media_Buy_Target_Audience");

  private static final org.apache.thrift.protocol.TField MEDIA_BUY_ID_FIELD_DESC = new org.apache.thrift.protocol.TField("mediaBuyID", org.apache.thrift.protocol.TType.I32, (short)1);
  private static final org.apache.thrift.protocol.TField STATUS_FIELD_DESC = new org.apache.thrift.protocol.TField("status", org.apache.thrift.protocol.TType.I32, (short)2);
  private static final org.apache.thrift.protocol.TField LAST_CHANGED_FIELD_DESC = new org.apache.thrift.protocol.TField("lastChanged", org.apache.thrift.protocol.TType.STRING, (short)3);
  private static final org.apache.thrift.protocol.TField TARGET_AUDIENCE_FIELD_DESC = new org.apache.thrift.protocol.TField("targetAudience", org.apache.thrift.protocol.TType.STRING, (short)4);
  private static final org.apache.thrift.protocol.TField TARGET_AUDIENCE_RULES_FIELD_DESC = new org.apache.thrift.protocol.TField("targetAudienceRules", org.apache.thrift.protocol.TType.STRING, (short)5);
  private static final org.apache.thrift.protocol.TField CTURL_RULES_FIELD_DESC = new org.apache.thrift.protocol.TField("cturlRules", org.apache.thrift.protocol.TType.STRING, (short)6);
  private static final org.apache.thrift.protocol.TField KEYWORD_RULES_FIELD_DESC = new org.apache.thrift.protocol.TField("keywordRules", org.apache.thrift.protocol.TType.STRING, (short)7);
  private static final org.apache.thrift.protocol.TField DEMOGRAPHIC_RULES_FIELD_DESC = new org.apache.thrift.protocol.TField("demographicRules", org.apache.thrift.protocol.TType.STRING, (short)8);

  private static final Map<Class<? extends IScheme>, SchemeFactory> schemes = new HashMap<Class<? extends IScheme>, SchemeFactory>();
  static {
    schemes.put(StandardScheme.class, new TDbSync_Dsp_Media_Buy_Target_AudienceStandardSchemeFactory());
    schemes.put(TupleScheme.class, new TDbSync_Dsp_Media_Buy_Target_AudienceTupleSchemeFactory());
  }

  public int mediaBuyID; // required
  public int status; // required
  public String lastChanged; // required
  public String targetAudience; // required
  public String targetAudienceRules; // required
  public String cturlRules; // required
  public String keywordRules; // required
  public String demographicRules; // required

  /** The set of fields this struct contains, along with convenience methods for finding and manipulating them. */
  public enum _Fields implements org.apache.thrift.TFieldIdEnum {
    MEDIA_BUY_ID((short)1, "mediaBuyID"),
    STATUS((short)2, "status"),
    LAST_CHANGED((short)3, "lastChanged"),
    TARGET_AUDIENCE((short)4, "targetAudience"),
    TARGET_AUDIENCE_RULES((short)5, "targetAudienceRules"),
    CTURL_RULES((short)6, "cturlRules"),
    KEYWORD_RULES((short)7, "keywordRules"),
    DEMOGRAPHIC_RULES((short)8, "demographicRules");

    private static final Map<String, _Fields> byName = new HashMap<String, _Fields>();

    static {
      for (_Fields field : EnumSet.allOf(_Fields.class)) {
        byName.put(field.getFieldName(), field);
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, or null if its not found.
     */
    public static _Fields findByThriftId(int fieldId) {
      switch(fieldId) {
        case 1: // MEDIA_BUY_ID
          return MEDIA_BUY_ID;
        case 2: // STATUS
          return STATUS;
        case 3: // LAST_CHANGED
          return LAST_CHANGED;
        case 4: // TARGET_AUDIENCE
          return TARGET_AUDIENCE;
        case 5: // TARGET_AUDIENCE_RULES
          return TARGET_AUDIENCE_RULES;
        case 6: // CTURL_RULES
          return CTURL_RULES;
        case 7: // KEYWORD_RULES
          return KEYWORD_RULES;
        case 8: // DEMOGRAPHIC_RULES
          return DEMOGRAPHIC_RULES;
        default:
          return null;
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, throwing an exception
     * if it is not found.
     */
    public static _Fields findByThriftIdOrThrow(int fieldId) {
      _Fields fields = findByThriftId(fieldId);
      if (fields == null) throw new IllegalArgumentException("Field " + fieldId + " doesn't exist!");
      return fields;
    }

    /**
     * Find the _Fields constant that matches name, or null if its not found.
     */
    public static _Fields findByName(String name) {
      return byName.get(name);
    }

    private final short _thriftId;
    private final String _fieldName;

    _Fields(short thriftId, String fieldName) {
      _thriftId = thriftId;
      _fieldName = fieldName;
    }

    public short getThriftFieldId() {
      return _thriftId;
    }

    public String getFieldName() {
      return _fieldName;
    }
  }

  // isset id assignments
  private static final int __MEDIABUYID_ISSET_ID = 0;
  private static final int __STATUS_ISSET_ID = 1;
  private byte __isset_bitfield = 0;
  public static final Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> metaDataMap;
  static {
    Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> tmpMap = new EnumMap<_Fields, org.apache.thrift.meta_data.FieldMetaData>(_Fields.class);
    tmpMap.put(_Fields.MEDIA_BUY_ID, new org.apache.thrift.meta_data.FieldMetaData("mediaBuyID", org.apache.thrift.TFieldRequirementType.REQUIRED, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.I32)));
    tmpMap.put(_Fields.STATUS, new org.apache.thrift.meta_data.FieldMetaData("status", org.apache.thrift.TFieldRequirementType.REQUIRED, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.I32)));
    tmpMap.put(_Fields.LAST_CHANGED, new org.apache.thrift.meta_data.FieldMetaData("lastChanged", org.apache.thrift.TFieldRequirementType.REQUIRED, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.STRING)));
    tmpMap.put(_Fields.TARGET_AUDIENCE, new org.apache.thrift.meta_data.FieldMetaData("targetAudience", org.apache.thrift.TFieldRequirementType.REQUIRED, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.STRING)));
    tmpMap.put(_Fields.TARGET_AUDIENCE_RULES, new org.apache.thrift.meta_data.FieldMetaData("targetAudienceRules", org.apache.thrift.TFieldRequirementType.REQUIRED, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.STRING)));
    tmpMap.put(_Fields.CTURL_RULES, new org.apache.thrift.meta_data.FieldMetaData("cturlRules", org.apache.thrift.TFieldRequirementType.REQUIRED, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.STRING)));
    tmpMap.put(_Fields.KEYWORD_RULES, new org.apache.thrift.meta_data.FieldMetaData("keywordRules", org.apache.thrift.TFieldRequirementType.REQUIRED, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.STRING)));
    tmpMap.put(_Fields.DEMOGRAPHIC_RULES, new org.apache.thrift.meta_data.FieldMetaData("demographicRules", org.apache.thrift.TFieldRequirementType.REQUIRED, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.STRING)));
    metaDataMap = Collections.unmodifiableMap(tmpMap);
    org.apache.thrift.meta_data.FieldMetaData.addStructMetaDataMap(TDbSync_Dsp_Media_Buy_Target_Audience.class, metaDataMap);
  }

  public TDbSync_Dsp_Media_Buy_Target_Audience() {
  }

  public TDbSync_Dsp_Media_Buy_Target_Audience(
    int mediaBuyID,
    int status,
    String lastChanged,
    String targetAudience,
    String targetAudienceRules,
    String cturlRules,
    String keywordRules,
    String demographicRules)
  {
    this();
    this.mediaBuyID = mediaBuyID;
    setMediaBuyIDIsSet(true);
    this.status = status;
    setStatusIsSet(true);
    this.lastChanged = lastChanged;
    this.targetAudience = targetAudience;
    this.targetAudienceRules = targetAudienceRules;
    this.cturlRules = cturlRules;
    this.keywordRules = keywordRules;
    this.demographicRules = demographicRules;
  }

  /**
   * Performs a deep copy on <i>other</i>.
   */
  public TDbSync_Dsp_Media_Buy_Target_Audience(TDbSync_Dsp_Media_Buy_Target_Audience other) {
    __isset_bitfield = other.__isset_bitfield;
    this.mediaBuyID = other.mediaBuyID;
    this.status = other.status;
    if (other.isSetLastChanged()) {
      this.lastChanged = other.lastChanged;
    }
    if (other.isSetTargetAudience()) {
      this.targetAudience = other.targetAudience;
    }
    if (other.isSetTargetAudienceRules()) {
      this.targetAudienceRules = other.targetAudienceRules;
    }
    if (other.isSetCturlRules()) {
      this.cturlRules = other.cturlRules;
    }
    if (other.isSetKeywordRules()) {
      this.keywordRules = other.keywordRules;
    }
    if (other.isSetDemographicRules()) {
      this.demographicRules = other.demographicRules;
    }
  }

  public TDbSync_Dsp_Media_Buy_Target_Audience deepCopy() {
    return new TDbSync_Dsp_Media_Buy_Target_Audience(this);
  }

  @Override
  public void clear() {
    setMediaBuyIDIsSet(false);
    this.mediaBuyID = 0;
    setStatusIsSet(false);
    this.status = 0;
    this.lastChanged = null;
    this.targetAudience = null;
    this.targetAudienceRules = null;
    this.cturlRules = null;
    this.keywordRules = null;
    this.demographicRules = null;
  }

  public int getMediaBuyID() {
    return this.mediaBuyID;
  }

  public TDbSync_Dsp_Media_Buy_Target_Audience setMediaBuyID(int mediaBuyID) {
    this.mediaBuyID = mediaBuyID;
    setMediaBuyIDIsSet(true);
    return this;
  }

  public void unsetMediaBuyID() {
    __isset_bitfield = EncodingUtils.clearBit(__isset_bitfield, __MEDIABUYID_ISSET_ID);
  }

  /** Returns true if field mediaBuyID is set (has been assigned a value) and false otherwise */
  public boolean isSetMediaBuyID() {
    return EncodingUtils.testBit(__isset_bitfield, __MEDIABUYID_ISSET_ID);
  }

  public void setMediaBuyIDIsSet(boolean value) {
    __isset_bitfield = EncodingUtils.setBit(__isset_bitfield, __MEDIABUYID_ISSET_ID, value);
  }

  public int getStatus() {
    return this.status;
  }

  public TDbSync_Dsp_Media_Buy_Target_Audience setStatus(int status) {
    this.status = status;
    setStatusIsSet(true);
    return this;
  }

  public void unsetStatus() {
    __isset_bitfield = EncodingUtils.clearBit(__isset_bitfield, __STATUS_ISSET_ID);
  }

  /** Returns true if field status is set (has been assigned a value) and false otherwise */
  public boolean isSetStatus() {
    return EncodingUtils.testBit(__isset_bitfield, __STATUS_ISSET_ID);
  }

  public void setStatusIsSet(boolean value) {
    __isset_bitfield = EncodingUtils.setBit(__isset_bitfield, __STATUS_ISSET_ID, value);
  }

  public String getLastChanged() {
    return this.lastChanged;
  }

  public TDbSync_Dsp_Media_Buy_Target_Audience setLastChanged(String lastChanged) {
    this.lastChanged = lastChanged;
    return this;
  }

  public void unsetLastChanged() {
    this.lastChanged = null;
  }

  /** Returns true if field lastChanged is set (has been assigned a value) and false otherwise */
  public boolean isSetLastChanged() {
    return this.lastChanged != null;
  }

  public void setLastChangedIsSet(boolean value) {
    if (!value) {
      this.lastChanged = null;
    }
  }

  public String getTargetAudience() {
    return this.targetAudience;
  }

  public TDbSync_Dsp_Media_Buy_Target_Audience setTargetAudience(String targetAudience) {
    this.targetAudience = targetAudience;
    return this;
  }

  public void unsetTargetAudience() {
    this.targetAudience = null;
  }

  /** Returns true if field targetAudience is set (has been assigned a value) and false otherwise */
  public boolean isSetTargetAudience() {
    return this.targetAudience != null;
  }

  public void setTargetAudienceIsSet(boolean value) {
    if (!value) {
      this.targetAudience = null;
    }
  }

  public String getTargetAudienceRules() {
    return this.targetAudienceRules;
  }

  public TDbSync_Dsp_Media_Buy_Target_Audience setTargetAudienceRules(String targetAudienceRules) {
    this.targetAudienceRules = targetAudienceRules;
    return this;
  }

  public void unsetTargetAudienceRules() {
    this.targetAudienceRules = null;
  }

  /** Returns true if field targetAudienceRules is set (has been assigned a value) and false otherwise */
  public boolean isSetTargetAudienceRules() {
    return this.targetAudienceRules != null;
  }

  public void setTargetAudienceRulesIsSet(boolean value) {
    if (!value) {
      this.targetAudienceRules = null;
    }
  }

  public String getCturlRules() {
    return this.cturlRules;
  }

  public TDbSync_Dsp_Media_Buy_Target_Audience setCturlRules(String cturlRules) {
    this.cturlRules = cturlRules;
    return this;
  }

  public void unsetCturlRules() {
    this.cturlRules = null;
  }

  /** Returns true if field cturlRules is set (has been assigned a value) and false otherwise */
  public boolean isSetCturlRules() {
    return this.cturlRules != null;
  }

  public void setCturlRulesIsSet(boolean value) {
    if (!value) {
      this.cturlRules = null;
    }
  }

  public String getKeywordRules() {
    return this.keywordRules;
  }

  public TDbSync_Dsp_Media_Buy_Target_Audience setKeywordRules(String keywordRules) {
    this.keywordRules = keywordRules;
    return this;
  }

  public void unsetKeywordRules() {
    this.keywordRules = null;
  }

  /** Returns true if field keywordRules is set (has been assigned a value) and false otherwise */
  public boolean isSetKeywordRules() {
    return this.keywordRules != null;
  }

  public void setKeywordRulesIsSet(boolean value) {
    if (!value) {
      this.keywordRules = null;
    }
  }

  public String getDemographicRules() {
    return this.demographicRules;
  }

  public TDbSync_Dsp_Media_Buy_Target_Audience setDemographicRules(String demographicRules) {
    this.demographicRules = demographicRules;
    return this;
  }

  public void unsetDemographicRules() {
    this.demographicRules = null;
  }

  /** Returns true if field demographicRules is set (has been assigned a value) and false otherwise */
  public boolean isSetDemographicRules() {
    return this.demographicRules != null;
  }

  public void setDemographicRulesIsSet(boolean value) {
    if (!value) {
      this.demographicRules = null;
    }
  }

  public void setFieldValue(_Fields field, Object value) {
    switch (field) {
    case MEDIA_BUY_ID:
      if (value == null) {
        unsetMediaBuyID();
      } else {
        setMediaBuyID((Integer)value);
      }
      break;

    case STATUS:
      if (value == null) {
        unsetStatus();
      } else {
        setStatus((Integer)value);
      }
      break;

    case LAST_CHANGED:
      if (value == null) {
        unsetLastChanged();
      } else {
        setLastChanged((String)value);
      }
      break;

    case TARGET_AUDIENCE:
      if (value == null) {
        unsetTargetAudience();
      } else {
        setTargetAudience((String)value);
      }
      break;

    case TARGET_AUDIENCE_RULES:
      if (value == null) {
        unsetTargetAudienceRules();
      } else {
        setTargetAudienceRules((String)value);
      }
      break;

    case CTURL_RULES:
      if (value == null) {
        unsetCturlRules();
      } else {
        setCturlRules((String)value);
      }
      break;

    case KEYWORD_RULES:
      if (value == null) {
        unsetKeywordRules();
      } else {
        setKeywordRules((String)value);
      }
      break;

    case DEMOGRAPHIC_RULES:
      if (value == null) {
        unsetDemographicRules();
      } else {
        setDemographicRules((String)value);
      }
      break;

    }
  }

  public Object getFieldValue(_Fields field) {
    switch (field) {
    case MEDIA_BUY_ID:
      return Integer.valueOf(getMediaBuyID());

    case STATUS:
      return Integer.valueOf(getStatus());

    case LAST_CHANGED:
      return getLastChanged();

    case TARGET_AUDIENCE:
      return getTargetAudience();

    case TARGET_AUDIENCE_RULES:
      return getTargetAudienceRules();

    case CTURL_RULES:
      return getCturlRules();

    case KEYWORD_RULES:
      return getKeywordRules();

    case DEMOGRAPHIC_RULES:
      return getDemographicRules();

    }
    throw new IllegalStateException();
  }

  /** Returns true if field corresponding to fieldID is set (has been assigned a value) and false otherwise */
  public boolean isSet(_Fields field) {
    if (field == null) {
      throw new IllegalArgumentException();
    }

    switch (field) {
    case MEDIA_BUY_ID:
      return isSetMediaBuyID();
    case STATUS:
      return isSetStatus();
    case LAST_CHANGED:
      return isSetLastChanged();
    case TARGET_AUDIENCE:
      return isSetTargetAudience();
    case TARGET_AUDIENCE_RULES:
      return isSetTargetAudienceRules();
    case CTURL_RULES:
      return isSetCturlRules();
    case KEYWORD_RULES:
      return isSetKeywordRules();
    case DEMOGRAPHIC_RULES:
      return isSetDemographicRules();
    }
    throw new IllegalStateException();
  }

  @Override
  public boolean equals(Object that) {
    if (that == null)
      return false;
    if (that instanceof TDbSync_Dsp_Media_Buy_Target_Audience)
      return this.equals((TDbSync_Dsp_Media_Buy_Target_Audience)that);
    return false;
  }

  public boolean equals(TDbSync_Dsp_Media_Buy_Target_Audience that) {
    if (that == null)
      return false;

    boolean this_present_mediaBuyID = true;
    boolean that_present_mediaBuyID = true;
    if (this_present_mediaBuyID || that_present_mediaBuyID) {
      if (!(this_present_mediaBuyID && that_present_mediaBuyID))
        return false;
      if (this.mediaBuyID != that.mediaBuyID)
        return false;
    }

    boolean this_present_status = true;
    boolean that_present_status = true;
    if (this_present_status || that_present_status) {
      if (!(this_present_status && that_present_status))
        return false;
      if (this.status != that.status)
        return false;
    }

    boolean this_present_lastChanged = true && this.isSetLastChanged();
    boolean that_present_lastChanged = true && that.isSetLastChanged();
    if (this_present_lastChanged || that_present_lastChanged) {
      if (!(this_present_lastChanged && that_present_lastChanged))
        return false;
      if (!this.lastChanged.equals(that.lastChanged))
        return false;
    }

    boolean this_present_targetAudience = true && this.isSetTargetAudience();
    boolean that_present_targetAudience = true && that.isSetTargetAudience();
    if (this_present_targetAudience || that_present_targetAudience) {
      if (!(this_present_targetAudience && that_present_targetAudience))
        return false;
      if (!this.targetAudience.equals(that.targetAudience))
        return false;
    }

    boolean this_present_targetAudienceRules = true && this.isSetTargetAudienceRules();
    boolean that_present_targetAudienceRules = true && that.isSetTargetAudienceRules();
    if (this_present_targetAudienceRules || that_present_targetAudienceRules) {
      if (!(this_present_targetAudienceRules && that_present_targetAudienceRules))
        return false;
      if (!this.targetAudienceRules.equals(that.targetAudienceRules))
        return false;
    }

    boolean this_present_cturlRules = true && this.isSetCturlRules();
    boolean that_present_cturlRules = true && that.isSetCturlRules();
    if (this_present_cturlRules || that_present_cturlRules) {
      if (!(this_present_cturlRules && that_present_cturlRules))
        return false;
      if (!this.cturlRules.equals(that.cturlRules))
        return false;
    }

    boolean this_present_keywordRules = true && this.isSetKeywordRules();
    boolean that_present_keywordRules = true && that.isSetKeywordRules();
    if (this_present_keywordRules || that_present_keywordRules) {
      if (!(this_present_keywordRules && that_present_keywordRules))
        return false;
      if (!this.keywordRules.equals(that.keywordRules))
        return false;
    }

    boolean this_present_demographicRules = true && this.isSetDemographicRules();
    boolean that_present_demographicRules = true && that.isSetDemographicRules();
    if (this_present_demographicRules || that_present_demographicRules) {
      if (!(this_present_demographicRules && that_present_demographicRules))
        return false;
      if (!this.demographicRules.equals(that.demographicRules))
        return false;
    }

    return true;
  }

  @Override
  public int hashCode() {
    return 0;
  }

  @Override
  public int compareTo(TDbSync_Dsp_Media_Buy_Target_Audience other) {
    if (!getClass().equals(other.getClass())) {
      return getClass().getName().compareTo(other.getClass().getName());
    }

    int lastComparison = 0;

    lastComparison = Boolean.valueOf(isSetMediaBuyID()).compareTo(other.isSetMediaBuyID());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetMediaBuyID()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.mediaBuyID, other.mediaBuyID);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = Boolean.valueOf(isSetStatus()).compareTo(other.isSetStatus());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetStatus()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.status, other.status);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = Boolean.valueOf(isSetLastChanged()).compareTo(other.isSetLastChanged());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetLastChanged()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.lastChanged, other.lastChanged);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = Boolean.valueOf(isSetTargetAudience()).compareTo(other.isSetTargetAudience());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetTargetAudience()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.targetAudience, other.targetAudience);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = Boolean.valueOf(isSetTargetAudienceRules()).compareTo(other.isSetTargetAudienceRules());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetTargetAudienceRules()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.targetAudienceRules, other.targetAudienceRules);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = Boolean.valueOf(isSetCturlRules()).compareTo(other.isSetCturlRules());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetCturlRules()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.cturlRules, other.cturlRules);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = Boolean.valueOf(isSetKeywordRules()).compareTo(other.isSetKeywordRules());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetKeywordRules()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.keywordRules, other.keywordRules);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = Boolean.valueOf(isSetDemographicRules()).compareTo(other.isSetDemographicRules());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetDemographicRules()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.demographicRules, other.demographicRules);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    return 0;
  }

  public _Fields fieldForId(int fieldId) {
    return _Fields.findByThriftId(fieldId);
  }

  public void read(org.apache.thrift.protocol.TProtocol iprot) throws org.apache.thrift.TException {
    schemes.get(iprot.getScheme()).getScheme().read(iprot, this);
  }

  public void write(org.apache.thrift.protocol.TProtocol oprot) throws org.apache.thrift.TException {
    schemes.get(oprot.getScheme()).getScheme().write(oprot, this);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder("TDbSync_Dsp_Media_Buy_Target_Audience(");
    boolean first = true;

    sb.append("mediaBuyID:");
    sb.append(this.mediaBuyID);
    first = false;
    if (!first) sb.append(", ");
    sb.append("status:");
    sb.append(this.status);
    first = false;
    if (!first) sb.append(", ");
    sb.append("lastChanged:");
    if (this.lastChanged == null) {
      sb.append("null");
    } else {
      sb.append(this.lastChanged);
    }
    first = false;
    if (!first) sb.append(", ");
    sb.append("targetAudience:");
    if (this.targetAudience == null) {
      sb.append("null");
    } else {
      sb.append(this.targetAudience);
    }
    first = false;
    if (!first) sb.append(", ");
    sb.append("targetAudienceRules:");
    if (this.targetAudienceRules == null) {
      sb.append("null");
    } else {
      sb.append(this.targetAudienceRules);
    }
    first = false;
    if (!first) sb.append(", ");
    sb.append("cturlRules:");
    if (this.cturlRules == null) {
      sb.append("null");
    } else {
      sb.append(this.cturlRules);
    }
    first = false;
    if (!first) sb.append(", ");
    sb.append("keywordRules:");
    if (this.keywordRules == null) {
      sb.append("null");
    } else {
      sb.append(this.keywordRules);
    }
    first = false;
    if (!first) sb.append(", ");
    sb.append("demographicRules:");
    if (this.demographicRules == null) {
      sb.append("null");
    } else {
      sb.append(this.demographicRules);
    }
    first = false;
    sb.append(")");
    return sb.toString();
  }

  public void validate() throws org.apache.thrift.TException {
    // check for required fields
    // alas, we cannot check 'mediaBuyID' because it's a primitive and you chose the non-beans generator.
    // alas, we cannot check 'status' because it's a primitive and you chose the non-beans generator.
    if (lastChanged == null) {
      throw new org.apache.thrift.protocol.TProtocolException("Required field 'lastChanged' was not present! Struct: " + toString());
    }
    if (targetAudience == null) {
      throw new org.apache.thrift.protocol.TProtocolException("Required field 'targetAudience' was not present! Struct: " + toString());
    }
    if (targetAudienceRules == null) {
      throw new org.apache.thrift.protocol.TProtocolException("Required field 'targetAudienceRules' was not present! Struct: " + toString());
    }
    if (cturlRules == null) {
      throw new org.apache.thrift.protocol.TProtocolException("Required field 'cturlRules' was not present! Struct: " + toString());
    }
    if (keywordRules == null) {
      throw new org.apache.thrift.protocol.TProtocolException("Required field 'keywordRules' was not present! Struct: " + toString());
    }
    if (demographicRules == null) {
      throw new org.apache.thrift.protocol.TProtocolException("Required field 'demographicRules' was not present! Struct: " + toString());
    }
    // check for sub-struct validity
  }

  private void writeObject(java.io.ObjectOutputStream out) throws java.io.IOException {
    try {
      write(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(out)));
    } catch (org.apache.thrift.TException te) {
      throw new java.io.IOException(te);
    }
  }

  private void readObject(java.io.ObjectInputStream in) throws java.io.IOException, ClassNotFoundException {
    try {
      // it doesn't seem like you should have to do this, but java serialization is wacky, and doesn't call the default constructor.
      __isset_bitfield = 0;
      read(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(in)));
    } catch (org.apache.thrift.TException te) {
      throw new java.io.IOException(te);
    }
  }

  private static class TDbSync_Dsp_Media_Buy_Target_AudienceStandardSchemeFactory implements SchemeFactory {
    public TDbSync_Dsp_Media_Buy_Target_AudienceStandardScheme getScheme() {
      return new TDbSync_Dsp_Media_Buy_Target_AudienceStandardScheme();
    }
  }

  private static class TDbSync_Dsp_Media_Buy_Target_AudienceStandardScheme extends StandardScheme<TDbSync_Dsp_Media_Buy_Target_Audience> {

    public void read(org.apache.thrift.protocol.TProtocol iprot, TDbSync_Dsp_Media_Buy_Target_Audience struct) throws org.apache.thrift.TException {
      org.apache.thrift.protocol.TField schemeField;
      iprot.readStructBegin();
      while (true)
      {
        schemeField = iprot.readFieldBegin();
        if (schemeField.type == org.apache.thrift.protocol.TType.STOP) { 
          break;
        }
        switch (schemeField.id) {
          case 1: // MEDIA_BUY_ID
            if (schemeField.type == org.apache.thrift.protocol.TType.I32) {
              struct.mediaBuyID = iprot.readI32();
              struct.setMediaBuyIDIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 2: // STATUS
            if (schemeField.type == org.apache.thrift.protocol.TType.I32) {
              struct.status = iprot.readI32();
              struct.setStatusIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 3: // LAST_CHANGED
            if (schemeField.type == org.apache.thrift.protocol.TType.STRING) {
              struct.lastChanged = iprot.readString();
              struct.setLastChangedIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 4: // TARGET_AUDIENCE
            if (schemeField.type == org.apache.thrift.protocol.TType.STRING) {
              struct.targetAudience = iprot.readString();
              struct.setTargetAudienceIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 5: // TARGET_AUDIENCE_RULES
            if (schemeField.type == org.apache.thrift.protocol.TType.STRING) {
              struct.targetAudienceRules = iprot.readString();
              struct.setTargetAudienceRulesIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 6: // CTURL_RULES
            if (schemeField.type == org.apache.thrift.protocol.TType.STRING) {
              struct.cturlRules = iprot.readString();
              struct.setCturlRulesIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 7: // KEYWORD_RULES
            if (schemeField.type == org.apache.thrift.protocol.TType.STRING) {
              struct.keywordRules = iprot.readString();
              struct.setKeywordRulesIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 8: // DEMOGRAPHIC_RULES
            if (schemeField.type == org.apache.thrift.protocol.TType.STRING) {
              struct.demographicRules = iprot.readString();
              struct.setDemographicRulesIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          default:
            org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
        }
        iprot.readFieldEnd();
      }
      iprot.readStructEnd();

      // check for required fields of primitive type, which can't be checked in the validate method
      if (!struct.isSetMediaBuyID()) {
        throw new org.apache.thrift.protocol.TProtocolException("Required field 'mediaBuyID' was not found in serialized data! Struct: " + toString());
      }
      if (!struct.isSetStatus()) {
        throw new org.apache.thrift.protocol.TProtocolException("Required field 'status' was not found in serialized data! Struct: " + toString());
      }
      struct.validate();
    }

    public void write(org.apache.thrift.protocol.TProtocol oprot, TDbSync_Dsp_Media_Buy_Target_Audience struct) throws org.apache.thrift.TException {
      struct.validate();

      oprot.writeStructBegin(STRUCT_DESC);
      oprot.writeFieldBegin(MEDIA_BUY_ID_FIELD_DESC);
      oprot.writeI32(struct.mediaBuyID);
      oprot.writeFieldEnd();
      oprot.writeFieldBegin(STATUS_FIELD_DESC);
      oprot.writeI32(struct.status);
      oprot.writeFieldEnd();
      if (struct.lastChanged != null) {
        oprot.writeFieldBegin(LAST_CHANGED_FIELD_DESC);
        oprot.writeString(struct.lastChanged);
        oprot.writeFieldEnd();
      }
      if (struct.targetAudience != null) {
        oprot.writeFieldBegin(TARGET_AUDIENCE_FIELD_DESC);
        oprot.writeString(struct.targetAudience);
        oprot.writeFieldEnd();
      }
      if (struct.targetAudienceRules != null) {
        oprot.writeFieldBegin(TARGET_AUDIENCE_RULES_FIELD_DESC);
        oprot.writeString(struct.targetAudienceRules);
        oprot.writeFieldEnd();
      }
      if (struct.cturlRules != null) {
        oprot.writeFieldBegin(CTURL_RULES_FIELD_DESC);
        oprot.writeString(struct.cturlRules);
        oprot.writeFieldEnd();
      }
      if (struct.keywordRules != null) {
        oprot.writeFieldBegin(KEYWORD_RULES_FIELD_DESC);
        oprot.writeString(struct.keywordRules);
        oprot.writeFieldEnd();
      }
      if (struct.demographicRules != null) {
        oprot.writeFieldBegin(DEMOGRAPHIC_RULES_FIELD_DESC);
        oprot.writeString(struct.demographicRules);
        oprot.writeFieldEnd();
      }
      oprot.writeFieldStop();
      oprot.writeStructEnd();
    }

  }

  private static class TDbSync_Dsp_Media_Buy_Target_AudienceTupleSchemeFactory implements SchemeFactory {
    public TDbSync_Dsp_Media_Buy_Target_AudienceTupleScheme getScheme() {
      return new TDbSync_Dsp_Media_Buy_Target_AudienceTupleScheme();
    }
  }

  private static class TDbSync_Dsp_Media_Buy_Target_AudienceTupleScheme extends TupleScheme<TDbSync_Dsp_Media_Buy_Target_Audience> {

    @Override
    public void write(org.apache.thrift.protocol.TProtocol prot, TDbSync_Dsp_Media_Buy_Target_Audience struct) throws org.apache.thrift.TException {
      TTupleProtocol oprot = (TTupleProtocol) prot;
      oprot.writeI32(struct.mediaBuyID);
      oprot.writeI32(struct.status);
      oprot.writeString(struct.lastChanged);
      oprot.writeString(struct.targetAudience);
      oprot.writeString(struct.targetAudienceRules);
      oprot.writeString(struct.cturlRules);
      oprot.writeString(struct.keywordRules);
      oprot.writeString(struct.demographicRules);
    }

    @Override
    public void read(org.apache.thrift.protocol.TProtocol prot, TDbSync_Dsp_Media_Buy_Target_Audience struct) throws org.apache.thrift.TException {
      TTupleProtocol iprot = (TTupleProtocol) prot;
      struct.mediaBuyID = iprot.readI32();
      struct.setMediaBuyIDIsSet(true);
      struct.status = iprot.readI32();
      struct.setStatusIsSet(true);
      struct.lastChanged = iprot.readString();
      struct.setLastChangedIsSet(true);
      struct.targetAudience = iprot.readString();
      struct.setTargetAudienceIsSet(true);
      struct.targetAudienceRules = iprot.readString();
      struct.setTargetAudienceRulesIsSet(true);
      struct.cturlRules = iprot.readString();
      struct.setCturlRulesIsSet(true);
      struct.keywordRules = iprot.readString();
      struct.setKeywordRulesIsSet(true);
      struct.demographicRules = iprot.readString();
      struct.setDemographicRulesIsSet(true);
    }
  }

}

