/**
 * Autogenerated by Thrift Compiler (0.9.1)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package com.sidney.dbsyncserver.tserializ.dsp;

import org.apache.thrift.scheme.IScheme;
import org.apache.thrift.scheme.SchemeFactory;
import org.apache.thrift.scheme.StandardScheme;

import org.apache.thrift.scheme.TupleScheme;
import org.apache.thrift.protocol.TTupleProtocol;
import org.apache.thrift.protocol.TProtocolException;
import org.apache.thrift.EncodingUtils;
import org.apache.thrift.TException;
import org.apache.thrift.async.AsyncMethodCallback;
import org.apache.thrift.server.AbstractNonblockingServer.*;
import java.util.List;
import java.util.ArrayList;
import java.util.Map;
import java.util.HashMap;
import java.util.EnumMap;
import java.util.Set;
import java.util.HashSet;
import java.util.EnumSet;
import java.util.Collections;
import java.util.BitSet;
import java.nio.ByteBuffer;
import java.util.Arrays;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

public class TDbSync_Dsp_Campaign_Concept_Rotation implements org.apache.thrift.TBase<TDbSync_Dsp_Campaign_Concept_Rotation, TDbSync_Dsp_Campaign_Concept_Rotation._Fields>, java.io.Serializable, Cloneable, Comparable<TDbSync_Dsp_Campaign_Concept_Rotation> {
  private static final org.apache.thrift.protocol.TStruct STRUCT_DESC = new org.apache.thrift.protocol.TStruct("TDbSync_Dsp_Campaign_Concept_Rotation");

  private static final org.apache.thrift.protocol.TField CAMPAIGN_ID_FIELD_DESC = new org.apache.thrift.protocol.TField("campaignId", org.apache.thrift.protocol.TType.I32, (short)1);
  private static final org.apache.thrift.protocol.TField CONCEPT_ID_FIELD_DESC = new org.apache.thrift.protocol.TField("conceptId", org.apache.thrift.protocol.TType.I32, (short)2);
  private static final org.apache.thrift.protocol.TField SEQUENCE_FIELD_DESC = new org.apache.thrift.protocol.TField("sequence", org.apache.thrift.protocol.TType.I32, (short)3);
  private static final org.apache.thrift.protocol.TField WEIGHT_FIELD_DESC = new org.apache.thrift.protocol.TField("weight", org.apache.thrift.protocol.TType.STRING, (short)4);
  private static final org.apache.thrift.protocol.TField IMPRESSION_FIELD_DESC = new org.apache.thrift.protocol.TField("impression", org.apache.thrift.protocol.TType.I32, (short)5);
  private static final org.apache.thrift.protocol.TField CLICK_FIELD_DESC = new org.apache.thrift.protocol.TField("click", org.apache.thrift.protocol.TType.I32, (short)6);
  private static final org.apache.thrift.protocol.TField STATUS_FIELD_DESC = new org.apache.thrift.protocol.TField("Status", org.apache.thrift.protocol.TType.I32, (short)7);
  private static final org.apache.thrift.protocol.TField LAST_CHANGED_FIELD_DESC = new org.apache.thrift.protocol.TField("lastChanged", org.apache.thrift.protocol.TType.STRING, (short)8);

  private static final Map<Class<? extends IScheme>, SchemeFactory> schemes = new HashMap<Class<? extends IScheme>, SchemeFactory>();
  static {
    schemes.put(StandardScheme.class, new TDbSync_Dsp_Campaign_Concept_RotationStandardSchemeFactory());
    schemes.put(TupleScheme.class, new TDbSync_Dsp_Campaign_Concept_RotationTupleSchemeFactory());
  }

  public int campaignId; // required
  public int conceptId; // required
  public int sequence; // required
  public String weight; // required
  public int impression; // required
  public int click; // required
  public int Status; // required
  public String lastChanged; // required

  /** The set of fields this struct contains, along with convenience methods for finding and manipulating them. */
  public enum _Fields implements org.apache.thrift.TFieldIdEnum {
    CAMPAIGN_ID((short)1, "campaignId"),
    CONCEPT_ID((short)2, "conceptId"),
    SEQUENCE((short)3, "sequence"),
    WEIGHT((short)4, "weight"),
    IMPRESSION((short)5, "impression"),
    CLICK((short)6, "click"),
    STATUS((short)7, "Status"),
    LAST_CHANGED((short)8, "lastChanged");

    private static final Map<String, _Fields> byName = new HashMap<String, _Fields>();

    static {
      for (_Fields field : EnumSet.allOf(_Fields.class)) {
        byName.put(field.getFieldName(), field);
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, or null if its not found.
     */
    public static _Fields findByThriftId(int fieldId) {
      switch(fieldId) {
        case 1: // CAMPAIGN_ID
          return CAMPAIGN_ID;
        case 2: // CONCEPT_ID
          return CONCEPT_ID;
        case 3: // SEQUENCE
          return SEQUENCE;
        case 4: // WEIGHT
          return WEIGHT;
        case 5: // IMPRESSION
          return IMPRESSION;
        case 6: // CLICK
          return CLICK;
        case 7: // STATUS
          return STATUS;
        case 8: // LAST_CHANGED
          return LAST_CHANGED;
        default:
          return null;
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, throwing an exception
     * if it is not found.
     */
    public static _Fields findByThriftIdOrThrow(int fieldId) {
      _Fields fields = findByThriftId(fieldId);
      if (fields == null) throw new IllegalArgumentException("Field " + fieldId + " doesn't exist!");
      return fields;
    }

    /**
     * Find the _Fields constant that matches name, or null if its not found.
     */
    public static _Fields findByName(String name) {
      return byName.get(name);
    }

    private final short _thriftId;
    private final String _fieldName;

    _Fields(short thriftId, String fieldName) {
      _thriftId = thriftId;
      _fieldName = fieldName;
    }

    public short getThriftFieldId() {
      return _thriftId;
    }

    public String getFieldName() {
      return _fieldName;
    }
  }

  // isset id assignments
  private static final int __CAMPAIGNID_ISSET_ID = 0;
  private static final int __CONCEPTID_ISSET_ID = 1;
  private static final int __SEQUENCE_ISSET_ID = 2;
  private static final int __IMPRESSION_ISSET_ID = 3;
  private static final int __CLICK_ISSET_ID = 4;
  private static final int __STATUS_ISSET_ID = 5;
  private byte __isset_bitfield = 0;
  public static final Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> metaDataMap;
  static {
    Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> tmpMap = new EnumMap<_Fields, org.apache.thrift.meta_data.FieldMetaData>(_Fields.class);
    tmpMap.put(_Fields.CAMPAIGN_ID, new org.apache.thrift.meta_data.FieldMetaData("campaignId", org.apache.thrift.TFieldRequirementType.REQUIRED, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.I32)));
    tmpMap.put(_Fields.CONCEPT_ID, new org.apache.thrift.meta_data.FieldMetaData("conceptId", org.apache.thrift.TFieldRequirementType.REQUIRED, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.I32)));
    tmpMap.put(_Fields.SEQUENCE, new org.apache.thrift.meta_data.FieldMetaData("sequence", org.apache.thrift.TFieldRequirementType.REQUIRED, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.I32)));
    tmpMap.put(_Fields.WEIGHT, new org.apache.thrift.meta_data.FieldMetaData("weight", org.apache.thrift.TFieldRequirementType.REQUIRED, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.STRING)));
    tmpMap.put(_Fields.IMPRESSION, new org.apache.thrift.meta_data.FieldMetaData("impression", org.apache.thrift.TFieldRequirementType.REQUIRED, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.I32)));
    tmpMap.put(_Fields.CLICK, new org.apache.thrift.meta_data.FieldMetaData("click", org.apache.thrift.TFieldRequirementType.REQUIRED, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.I32)));
    tmpMap.put(_Fields.STATUS, new org.apache.thrift.meta_data.FieldMetaData("Status", org.apache.thrift.TFieldRequirementType.REQUIRED, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.I32)));
    tmpMap.put(_Fields.LAST_CHANGED, new org.apache.thrift.meta_data.FieldMetaData("lastChanged", org.apache.thrift.TFieldRequirementType.REQUIRED, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.STRING)));
    metaDataMap = Collections.unmodifiableMap(tmpMap);
    org.apache.thrift.meta_data.FieldMetaData.addStructMetaDataMap(TDbSync_Dsp_Campaign_Concept_Rotation.class, metaDataMap);
  }

  public TDbSync_Dsp_Campaign_Concept_Rotation() {
  }

  public TDbSync_Dsp_Campaign_Concept_Rotation(
    int campaignId,
    int conceptId,
    int sequence,
    String weight,
    int impression,
    int click,
    int Status,
    String lastChanged)
  {
    this();
    this.campaignId = campaignId;
    setCampaignIdIsSet(true);
    this.conceptId = conceptId;
    setConceptIdIsSet(true);
    this.sequence = sequence;
    setSequenceIsSet(true);
    this.weight = weight;
    this.impression = impression;
    setImpressionIsSet(true);
    this.click = click;
    setClickIsSet(true);
    this.Status = Status;
    setStatusIsSet(true);
    this.lastChanged = lastChanged;
  }

  /**
   * Performs a deep copy on <i>other</i>.
   */
  public TDbSync_Dsp_Campaign_Concept_Rotation(TDbSync_Dsp_Campaign_Concept_Rotation other) {
    __isset_bitfield = other.__isset_bitfield;
    this.campaignId = other.campaignId;
    this.conceptId = other.conceptId;
    this.sequence = other.sequence;
    if (other.isSetWeight()) {
      this.weight = other.weight;
    }
    this.impression = other.impression;
    this.click = other.click;
    this.Status = other.Status;
    if (other.isSetLastChanged()) {
      this.lastChanged = other.lastChanged;
    }
  }

  public TDbSync_Dsp_Campaign_Concept_Rotation deepCopy() {
    return new TDbSync_Dsp_Campaign_Concept_Rotation(this);
  }

  @Override
  public void clear() {
    setCampaignIdIsSet(false);
    this.campaignId = 0;
    setConceptIdIsSet(false);
    this.conceptId = 0;
    setSequenceIsSet(false);
    this.sequence = 0;
    this.weight = null;
    setImpressionIsSet(false);
    this.impression = 0;
    setClickIsSet(false);
    this.click = 0;
    setStatusIsSet(false);
    this.Status = 0;
    this.lastChanged = null;
  }

  public int getCampaignId() {
    return this.campaignId;
  }

  public TDbSync_Dsp_Campaign_Concept_Rotation setCampaignId(int campaignId) {
    this.campaignId = campaignId;
    setCampaignIdIsSet(true);
    return this;
  }

  public void unsetCampaignId() {
    __isset_bitfield = EncodingUtils.clearBit(__isset_bitfield, __CAMPAIGNID_ISSET_ID);
  }

  /** Returns true if field campaignId is set (has been assigned a value) and false otherwise */
  public boolean isSetCampaignId() {
    return EncodingUtils.testBit(__isset_bitfield, __CAMPAIGNID_ISSET_ID);
  }

  public void setCampaignIdIsSet(boolean value) {
    __isset_bitfield = EncodingUtils.setBit(__isset_bitfield, __CAMPAIGNID_ISSET_ID, value);
  }

  public int getConceptId() {
    return this.conceptId;
  }

  public TDbSync_Dsp_Campaign_Concept_Rotation setConceptId(int conceptId) {
    this.conceptId = conceptId;
    setConceptIdIsSet(true);
    return this;
  }

  public void unsetConceptId() {
    __isset_bitfield = EncodingUtils.clearBit(__isset_bitfield, __CONCEPTID_ISSET_ID);
  }

  /** Returns true if field conceptId is set (has been assigned a value) and false otherwise */
  public boolean isSetConceptId() {
    return EncodingUtils.testBit(__isset_bitfield, __CONCEPTID_ISSET_ID);
  }

  public void setConceptIdIsSet(boolean value) {
    __isset_bitfield = EncodingUtils.setBit(__isset_bitfield, __CONCEPTID_ISSET_ID, value);
  }

  public int getSequence() {
    return this.sequence;
  }

  public TDbSync_Dsp_Campaign_Concept_Rotation setSequence(int sequence) {
    this.sequence = sequence;
    setSequenceIsSet(true);
    return this;
  }

  public void unsetSequence() {
    __isset_bitfield = EncodingUtils.clearBit(__isset_bitfield, __SEQUENCE_ISSET_ID);
  }

  /** Returns true if field sequence is set (has been assigned a value) and false otherwise */
  public boolean isSetSequence() {
    return EncodingUtils.testBit(__isset_bitfield, __SEQUENCE_ISSET_ID);
  }

  public void setSequenceIsSet(boolean value) {
    __isset_bitfield = EncodingUtils.setBit(__isset_bitfield, __SEQUENCE_ISSET_ID, value);
  }

  public String getWeight() {
    return this.weight;
  }

  public TDbSync_Dsp_Campaign_Concept_Rotation setWeight(String weight) {
    this.weight = weight;
    return this;
  }

  public void unsetWeight() {
    this.weight = null;
  }

  /** Returns true if field weight is set (has been assigned a value) and false otherwise */
  public boolean isSetWeight() {
    return this.weight != null;
  }

  public void setWeightIsSet(boolean value) {
    if (!value) {
      this.weight = null;
    }
  }

  public int getImpression() {
    return this.impression;
  }

  public TDbSync_Dsp_Campaign_Concept_Rotation setImpression(int impression) {
    this.impression = impression;
    setImpressionIsSet(true);
    return this;
  }

  public void unsetImpression() {
    __isset_bitfield = EncodingUtils.clearBit(__isset_bitfield, __IMPRESSION_ISSET_ID);
  }

  /** Returns true if field impression is set (has been assigned a value) and false otherwise */
  public boolean isSetImpression() {
    return EncodingUtils.testBit(__isset_bitfield, __IMPRESSION_ISSET_ID);
  }

  public void setImpressionIsSet(boolean value) {
    __isset_bitfield = EncodingUtils.setBit(__isset_bitfield, __IMPRESSION_ISSET_ID, value);
  }

  public int getClick() {
    return this.click;
  }

  public TDbSync_Dsp_Campaign_Concept_Rotation setClick(int click) {
    this.click = click;
    setClickIsSet(true);
    return this;
  }

  public void unsetClick() {
    __isset_bitfield = EncodingUtils.clearBit(__isset_bitfield, __CLICK_ISSET_ID);
  }

  /** Returns true if field click is set (has been assigned a value) and false otherwise */
  public boolean isSetClick() {
    return EncodingUtils.testBit(__isset_bitfield, __CLICK_ISSET_ID);
  }

  public void setClickIsSet(boolean value) {
    __isset_bitfield = EncodingUtils.setBit(__isset_bitfield, __CLICK_ISSET_ID, value);
  }

  public int getStatus() {
    return this.Status;
  }

  public TDbSync_Dsp_Campaign_Concept_Rotation setStatus(int Status) {
    this.Status = Status;
    setStatusIsSet(true);
    return this;
  }

  public void unsetStatus() {
    __isset_bitfield = EncodingUtils.clearBit(__isset_bitfield, __STATUS_ISSET_ID);
  }

  /** Returns true if field Status is set (has been assigned a value) and false otherwise */
  public boolean isSetStatus() {
    return EncodingUtils.testBit(__isset_bitfield, __STATUS_ISSET_ID);
  }

  public void setStatusIsSet(boolean value) {
    __isset_bitfield = EncodingUtils.setBit(__isset_bitfield, __STATUS_ISSET_ID, value);
  }

  public String getLastChanged() {
    return this.lastChanged;
  }

  public TDbSync_Dsp_Campaign_Concept_Rotation setLastChanged(String lastChanged) {
    this.lastChanged = lastChanged;
    return this;
  }

  public void unsetLastChanged() {
    this.lastChanged = null;
  }

  /** Returns true if field lastChanged is set (has been assigned a value) and false otherwise */
  public boolean isSetLastChanged() {
    return this.lastChanged != null;
  }

  public void setLastChangedIsSet(boolean value) {
    if (!value) {
      this.lastChanged = null;
    }
  }

  public void setFieldValue(_Fields field, Object value) {
    switch (field) {
    case CAMPAIGN_ID:
      if (value == null) {
        unsetCampaignId();
      } else {
        setCampaignId((Integer)value);
      }
      break;

    case CONCEPT_ID:
      if (value == null) {
        unsetConceptId();
      } else {
        setConceptId((Integer)value);
      }
      break;

    case SEQUENCE:
      if (value == null) {
        unsetSequence();
      } else {
        setSequence((Integer)value);
      }
      break;

    case WEIGHT:
      if (value == null) {
        unsetWeight();
      } else {
        setWeight((String)value);
      }
      break;

    case IMPRESSION:
      if (value == null) {
        unsetImpression();
      } else {
        setImpression((Integer)value);
      }
      break;

    case CLICK:
      if (value == null) {
        unsetClick();
      } else {
        setClick((Integer)value);
      }
      break;

    case STATUS:
      if (value == null) {
        unsetStatus();
      } else {
        setStatus((Integer)value);
      }
      break;

    case LAST_CHANGED:
      if (value == null) {
        unsetLastChanged();
      } else {
        setLastChanged((String)value);
      }
      break;

    }
  }

  public Object getFieldValue(_Fields field) {
    switch (field) {
    case CAMPAIGN_ID:
      return Integer.valueOf(getCampaignId());

    case CONCEPT_ID:
      return Integer.valueOf(getConceptId());

    case SEQUENCE:
      return Integer.valueOf(getSequence());

    case WEIGHT:
      return getWeight();

    case IMPRESSION:
      return Integer.valueOf(getImpression());

    case CLICK:
      return Integer.valueOf(getClick());

    case STATUS:
      return Integer.valueOf(getStatus());

    case LAST_CHANGED:
      return getLastChanged();

    }
    throw new IllegalStateException();
  }

  /** Returns true if field corresponding to fieldID is set (has been assigned a value) and false otherwise */
  public boolean isSet(_Fields field) {
    if (field == null) {
      throw new IllegalArgumentException();
    }

    switch (field) {
    case CAMPAIGN_ID:
      return isSetCampaignId();
    case CONCEPT_ID:
      return isSetConceptId();
    case SEQUENCE:
      return isSetSequence();
    case WEIGHT:
      return isSetWeight();
    case IMPRESSION:
      return isSetImpression();
    case CLICK:
      return isSetClick();
    case STATUS:
      return isSetStatus();
    case LAST_CHANGED:
      return isSetLastChanged();
    }
    throw new IllegalStateException();
  }

  @Override
  public boolean equals(Object that) {
    if (that == null)
      return false;
    if (that instanceof TDbSync_Dsp_Campaign_Concept_Rotation)
      return this.equals((TDbSync_Dsp_Campaign_Concept_Rotation)that);
    return false;
  }

  public boolean equals(TDbSync_Dsp_Campaign_Concept_Rotation that) {
    if (that == null)
      return false;

    boolean this_present_campaignId = true;
    boolean that_present_campaignId = true;
    if (this_present_campaignId || that_present_campaignId) {
      if (!(this_present_campaignId && that_present_campaignId))
        return false;
      if (this.campaignId != that.campaignId)
        return false;
    }

    boolean this_present_conceptId = true;
    boolean that_present_conceptId = true;
    if (this_present_conceptId || that_present_conceptId) {
      if (!(this_present_conceptId && that_present_conceptId))
        return false;
      if (this.conceptId != that.conceptId)
        return false;
    }

    boolean this_present_sequence = true;
    boolean that_present_sequence = true;
    if (this_present_sequence || that_present_sequence) {
      if (!(this_present_sequence && that_present_sequence))
        return false;
      if (this.sequence != that.sequence)
        return false;
    }

    boolean this_present_weight = true && this.isSetWeight();
    boolean that_present_weight = true && that.isSetWeight();
    if (this_present_weight || that_present_weight) {
      if (!(this_present_weight && that_present_weight))
        return false;
      if (!this.weight.equals(that.weight))
        return false;
    }

    boolean this_present_impression = true;
    boolean that_present_impression = true;
    if (this_present_impression || that_present_impression) {
      if (!(this_present_impression && that_present_impression))
        return false;
      if (this.impression != that.impression)
        return false;
    }

    boolean this_present_click = true;
    boolean that_present_click = true;
    if (this_present_click || that_present_click) {
      if (!(this_present_click && that_present_click))
        return false;
      if (this.click != that.click)
        return false;
    }

    boolean this_present_Status = true;
    boolean that_present_Status = true;
    if (this_present_Status || that_present_Status) {
      if (!(this_present_Status && that_present_Status))
        return false;
      if (this.Status != that.Status)
        return false;
    }

    boolean this_present_lastChanged = true && this.isSetLastChanged();
    boolean that_present_lastChanged = true && that.isSetLastChanged();
    if (this_present_lastChanged || that_present_lastChanged) {
      if (!(this_present_lastChanged && that_present_lastChanged))
        return false;
      if (!this.lastChanged.equals(that.lastChanged))
        return false;
    }

    return true;
  }

  @Override
  public int hashCode() {
    return 0;
  }

  @Override
  public int compareTo(TDbSync_Dsp_Campaign_Concept_Rotation other) {
    if (!getClass().equals(other.getClass())) {
      return getClass().getName().compareTo(other.getClass().getName());
    }

    int lastComparison = 0;

    lastComparison = Boolean.valueOf(isSetCampaignId()).compareTo(other.isSetCampaignId());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetCampaignId()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.campaignId, other.campaignId);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = Boolean.valueOf(isSetConceptId()).compareTo(other.isSetConceptId());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetConceptId()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.conceptId, other.conceptId);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = Boolean.valueOf(isSetSequence()).compareTo(other.isSetSequence());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetSequence()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.sequence, other.sequence);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = Boolean.valueOf(isSetWeight()).compareTo(other.isSetWeight());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetWeight()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.weight, other.weight);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = Boolean.valueOf(isSetImpression()).compareTo(other.isSetImpression());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetImpression()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.impression, other.impression);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = Boolean.valueOf(isSetClick()).compareTo(other.isSetClick());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetClick()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.click, other.click);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = Boolean.valueOf(isSetStatus()).compareTo(other.isSetStatus());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetStatus()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.Status, other.Status);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = Boolean.valueOf(isSetLastChanged()).compareTo(other.isSetLastChanged());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetLastChanged()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.lastChanged, other.lastChanged);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    return 0;
  }

  public _Fields fieldForId(int fieldId) {
    return _Fields.findByThriftId(fieldId);
  }

  public void read(org.apache.thrift.protocol.TProtocol iprot) throws org.apache.thrift.TException {
    schemes.get(iprot.getScheme()).getScheme().read(iprot, this);
  }

  public void write(org.apache.thrift.protocol.TProtocol oprot) throws org.apache.thrift.TException {
    schemes.get(oprot.getScheme()).getScheme().write(oprot, this);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder("TDbSync_Dsp_Campaign_Concept_Rotation(");
    boolean first = true;

    sb.append("campaignId:");
    sb.append(this.campaignId);
    first = false;
    if (!first) sb.append(", ");
    sb.append("conceptId:");
    sb.append(this.conceptId);
    first = false;
    if (!first) sb.append(", ");
    sb.append("sequence:");
    sb.append(this.sequence);
    first = false;
    if (!first) sb.append(", ");
    sb.append("weight:");
    if (this.weight == null) {
      sb.append("null");
    } else {
      sb.append(this.weight);
    }
    first = false;
    if (!first) sb.append(", ");
    sb.append("impression:");
    sb.append(this.impression);
    first = false;
    if (!first) sb.append(", ");
    sb.append("click:");
    sb.append(this.click);
    first = false;
    if (!first) sb.append(", ");
    sb.append("Status:");
    sb.append(this.Status);
    first = false;
    if (!first) sb.append(", ");
    sb.append("lastChanged:");
    if (this.lastChanged == null) {
      sb.append("null");
    } else {
      sb.append(this.lastChanged);
    }
    first = false;
    sb.append(")");
    return sb.toString();
  }

  public void validate() throws org.apache.thrift.TException {
    // check for required fields
    // alas, we cannot check 'campaignId' because it's a primitive and you chose the non-beans generator.
    // alas, we cannot check 'conceptId' because it's a primitive and you chose the non-beans generator.
    // alas, we cannot check 'sequence' because it's a primitive and you chose the non-beans generator.
    if (weight == null) {
      throw new org.apache.thrift.protocol.TProtocolException("Required field 'weight' was not present! Struct: " + toString());
    }
    // alas, we cannot check 'impression' because it's a primitive and you chose the non-beans generator.
    // alas, we cannot check 'click' because it's a primitive and you chose the non-beans generator.
    // alas, we cannot check 'Status' because it's a primitive and you chose the non-beans generator.
    if (lastChanged == null) {
      throw new org.apache.thrift.protocol.TProtocolException("Required field 'lastChanged' was not present! Struct: " + toString());
    }
    // check for sub-struct validity
  }

  private void writeObject(java.io.ObjectOutputStream out) throws java.io.IOException {
    try {
      write(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(out)));
    } catch (org.apache.thrift.TException te) {
      throw new java.io.IOException(te);
    }
  }

  private void readObject(java.io.ObjectInputStream in) throws java.io.IOException, ClassNotFoundException {
    try {
      // it doesn't seem like you should have to do this, but java serialization is wacky, and doesn't call the default constructor.
      __isset_bitfield = 0;
      read(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(in)));
    } catch (org.apache.thrift.TException te) {
      throw new java.io.IOException(te);
    }
  }

  private static class TDbSync_Dsp_Campaign_Concept_RotationStandardSchemeFactory implements SchemeFactory {
    public TDbSync_Dsp_Campaign_Concept_RotationStandardScheme getScheme() {
      return new TDbSync_Dsp_Campaign_Concept_RotationStandardScheme();
    }
  }

  private static class TDbSync_Dsp_Campaign_Concept_RotationStandardScheme extends StandardScheme<TDbSync_Dsp_Campaign_Concept_Rotation> {

    public void read(org.apache.thrift.protocol.TProtocol iprot, TDbSync_Dsp_Campaign_Concept_Rotation struct) throws org.apache.thrift.TException {
      org.apache.thrift.protocol.TField schemeField;
      iprot.readStructBegin();
      while (true)
      {
        schemeField = iprot.readFieldBegin();
        if (schemeField.type == org.apache.thrift.protocol.TType.STOP) { 
          break;
        }
        switch (schemeField.id) {
          case 1: // CAMPAIGN_ID
            if (schemeField.type == org.apache.thrift.protocol.TType.I32) {
              struct.campaignId = iprot.readI32();
              struct.setCampaignIdIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 2: // CONCEPT_ID
            if (schemeField.type == org.apache.thrift.protocol.TType.I32) {
              struct.conceptId = iprot.readI32();
              struct.setConceptIdIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 3: // SEQUENCE
            if (schemeField.type == org.apache.thrift.protocol.TType.I32) {
              struct.sequence = iprot.readI32();
              struct.setSequenceIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 4: // WEIGHT
            if (schemeField.type == org.apache.thrift.protocol.TType.STRING) {
              struct.weight = iprot.readString();
              struct.setWeightIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 5: // IMPRESSION
            if (schemeField.type == org.apache.thrift.protocol.TType.I32) {
              struct.impression = iprot.readI32();
              struct.setImpressionIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 6: // CLICK
            if (schemeField.type == org.apache.thrift.protocol.TType.I32) {
              struct.click = iprot.readI32();
              struct.setClickIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 7: // STATUS
            if (schemeField.type == org.apache.thrift.protocol.TType.I32) {
              struct.Status = iprot.readI32();
              struct.setStatusIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 8: // LAST_CHANGED
            if (schemeField.type == org.apache.thrift.protocol.TType.STRING) {
              struct.lastChanged = iprot.readString();
              struct.setLastChangedIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          default:
            org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
        }
        iprot.readFieldEnd();
      }
      iprot.readStructEnd();

      // check for required fields of primitive type, which can't be checked in the validate method
      if (!struct.isSetCampaignId()) {
        throw new org.apache.thrift.protocol.TProtocolException("Required field 'campaignId' was not found in serialized data! Struct: " + toString());
      }
      if (!struct.isSetConceptId()) {
        throw new org.apache.thrift.protocol.TProtocolException("Required field 'conceptId' was not found in serialized data! Struct: " + toString());
      }
      if (!struct.isSetSequence()) {
        throw new org.apache.thrift.protocol.TProtocolException("Required field 'sequence' was not found in serialized data! Struct: " + toString());
      }
      if (!struct.isSetImpression()) {
        throw new org.apache.thrift.protocol.TProtocolException("Required field 'impression' was not found in serialized data! Struct: " + toString());
      }
      if (!struct.isSetClick()) {
        throw new org.apache.thrift.protocol.TProtocolException("Required field 'click' was not found in serialized data! Struct: " + toString());
      }
      if (!struct.isSetStatus()) {
        throw new org.apache.thrift.protocol.TProtocolException("Required field 'Status' was not found in serialized data! Struct: " + toString());
      }
      struct.validate();
    }

    public void write(org.apache.thrift.protocol.TProtocol oprot, TDbSync_Dsp_Campaign_Concept_Rotation struct) throws org.apache.thrift.TException {
      struct.validate();

      oprot.writeStructBegin(STRUCT_DESC);
      oprot.writeFieldBegin(CAMPAIGN_ID_FIELD_DESC);
      oprot.writeI32(struct.campaignId);
      oprot.writeFieldEnd();
      oprot.writeFieldBegin(CONCEPT_ID_FIELD_DESC);
      oprot.writeI32(struct.conceptId);
      oprot.writeFieldEnd();
      oprot.writeFieldBegin(SEQUENCE_FIELD_DESC);
      oprot.writeI32(struct.sequence);
      oprot.writeFieldEnd();
      if (struct.weight != null) {
        oprot.writeFieldBegin(WEIGHT_FIELD_DESC);
        oprot.writeString(struct.weight);
        oprot.writeFieldEnd();
      }
      oprot.writeFieldBegin(IMPRESSION_FIELD_DESC);
      oprot.writeI32(struct.impression);
      oprot.writeFieldEnd();
      oprot.writeFieldBegin(CLICK_FIELD_DESC);
      oprot.writeI32(struct.click);
      oprot.writeFieldEnd();
      oprot.writeFieldBegin(STATUS_FIELD_DESC);
      oprot.writeI32(struct.Status);
      oprot.writeFieldEnd();
      if (struct.lastChanged != null) {
        oprot.writeFieldBegin(LAST_CHANGED_FIELD_DESC);
        oprot.writeString(struct.lastChanged);
        oprot.writeFieldEnd();
      }
      oprot.writeFieldStop();
      oprot.writeStructEnd();
    }

  }

  private static class TDbSync_Dsp_Campaign_Concept_RotationTupleSchemeFactory implements SchemeFactory {
    public TDbSync_Dsp_Campaign_Concept_RotationTupleScheme getScheme() {
      return new TDbSync_Dsp_Campaign_Concept_RotationTupleScheme();
    }
  }

  private static class TDbSync_Dsp_Campaign_Concept_RotationTupleScheme extends TupleScheme<TDbSync_Dsp_Campaign_Concept_Rotation> {

    @Override
    public void write(org.apache.thrift.protocol.TProtocol prot, TDbSync_Dsp_Campaign_Concept_Rotation struct) throws org.apache.thrift.TException {
      TTupleProtocol oprot = (TTupleProtocol) prot;
      oprot.writeI32(struct.campaignId);
      oprot.writeI32(struct.conceptId);
      oprot.writeI32(struct.sequence);
      oprot.writeString(struct.weight);
      oprot.writeI32(struct.impression);
      oprot.writeI32(struct.click);
      oprot.writeI32(struct.Status);
      oprot.writeString(struct.lastChanged);
    }

    @Override
    public void read(org.apache.thrift.protocol.TProtocol prot, TDbSync_Dsp_Campaign_Concept_Rotation struct) throws org.apache.thrift.TException {
      TTupleProtocol iprot = (TTupleProtocol) prot;
      struct.campaignId = iprot.readI32();
      struct.setCampaignIdIsSet(true);
      struct.conceptId = iprot.readI32();
      struct.setConceptIdIsSet(true);
      struct.sequence = iprot.readI32();
      struct.setSequenceIsSet(true);
      struct.weight = iprot.readString();
      struct.setWeightIsSet(true);
      struct.impression = iprot.readI32();
      struct.setImpressionIsSet(true);
      struct.click = iprot.readI32();
      struct.setClickIsSet(true);
      struct.Status = iprot.readI32();
      struct.setStatusIsSet(true);
      struct.lastChanged = iprot.readString();
      struct.setLastChangedIsSet(true);
    }
  }

}

